version: '2'
services:
  repo3-app:
    image: repo3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://repo3-postgresql:5432/repo3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  repo3-postgresql:
    extends:
      file: postgresql.yml
      service: repo3-postgresql
